### PR TITLE
Devel sdkconfig defaults

### PR DESCRIPTION
**Pull request by ccrause**
Use sdkconfig.defaults files to only set non-default options.
Changed logging level for bootloader for debug/release modes.
Also set executable permission on esptool after copying (the x permission gets lost on Linux).

### CODE REVIEW

**Comment by michael-ring** [comment]
Thank you for the debug files!

**Comment by michael-ring** [comment]
I see that not libcoexist and libesp_coex are new as requirements, is this on purpose?

**Comment by ccrause** [comment]
I included the bluetooth and BLE mesh components, this then pulls in the coexist requirements.  It seems reasonable to enable use of BT functionality since it is part of the hardware features of the ESP family.  To remove this dependency from general builds would then require a separate BT build that depends on coexist & friends.

**Comment by michael-ring** [comment]
That makes sense, I was just wondering why the dependencies for 4.3.7 changed, mystery solved...

**Pull request merged**
