### PR TITLE
Update to latest stable SDK versions

### PR DESCRIPTION
**Pull request by ccrause**
Busy with testing, there may be a tweak or two missing yet.

### CODE REVIEW

**Comment by ccrause** [comment]
I picked up an issue with linking esp32, I suspect some precompiled library is missing in the copied list.

**Comment by michael-ring** [comment]
Thank you for the changes, testing now...

**Comment by michael-ring** [comment]
One question, you did not provide an updated version of the sdkconfig files for the new sdk's, are you ok with the esp-defaults (I think we changed serial line speed in the past) or, if not, can you please provide sdkconfig files that suit your needs.

**Comment by ccrause** [comment]
Yes, I forgot to add the new files.  Will try to add them to this branch.

**Pull request merged**
